# import necessary labraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from sklearn.model_selection import train_test_split

In [113]:
data=pd.read_excel('coin_Bitcoin.xlsx')
data

SNo     Name Symbol                Date          High           Low  \
0        1  Bitcoin    BTC 2013-04-29 23:59:59    147.488007    134.000000   
1        2  Bitcoin    BTC 2013-04-30 23:59:59    146.929993    134.050003   
2        3  Bitcoin    BTC 2013-05-01 23:59:59    139.889999    107.720001   
3        4  Bitcoin    BTC 2013-05-02 23:59:59    125.599998     92.281898   
4        5  Bitcoin    BTC 2013-05-03 23:59:59    108.127998     79.099998   
...    ...      ...    ...                 ...           ...           ...   
2986  2987  Bitcoin    BTC 2021-07-02 23:59:59  33939.588699  32770.680780   
2987  2988  Bitcoin    BTC 2021-07-03 23:59:59  34909.259899  33402.696536   
2988  2989  Bitcoin    BTC 2021-07-04 23:59:59  35937.567147  34396.477458   
2989  2990  Bitcoin    BTC 2021-07-05 23:59:59  35284.344430  33213.661034   
2990  2991  Bitcoin    BTC 2021-07-06 23:59:59  35038.536363  33599.916169   

              Open         Close        Volume     Marketcap  
0       134.444000    144.539993  0.000000e+00  1.603769e+09  
1       144.000000    139.000000  0.000000e+00  1.542813e+09  
2       139.000000    116.989998  0.000000e+00  1.298955e+09  
3       116.379997    105.209999  0.000000e+00  1.168517e+09  
4       106.250000     97.750000  0.000000e+00  1.085995e+09  
...            ...           ...           ...           ...  
2986  33549.600177  33897.048590  3.872897e+10  6.354508e+11  
2987  33854.421362  34668.548402  2.438396e+10  6.499397e+11  
2988  34665.564866  35287.779766  2.492431e+10  6.615748e+11  
2989  35284.344430  33746.002456  2.672155e+10  6.326962e+11  
2990  33723.509655  34235.193451  2.650126e+10  6.418992e+11  

[2991 rows x 10 columns]

In [114]:
data.drop(['SNo', 'Name', 'Symbol', 'Date', 'Open', 'Close'], axis=1, inplace=True)
data

High           Low        Volume     Marketcap
0       147.488007    134.000000  0.000000e+00  1.603769e+09
1       146.929993    134.050003  0.000000e+00  1.542813e+09
2       139.889999    107.720001  0.000000e+00  1.298955e+09
3       125.599998     92.281898  0.000000e+00  1.168517e+09
4       108.127998     79.099998  0.000000e+00  1.085995e+09
...            ...           ...           ...           ...
2986  33939.588699  32770.680780  3.872897e+10  6.354508e+11
2987  34909.259899  33402.696536  2.438396e+10  6.499397e+11
2988  35937.567147  34396.477458  2.492431e+10  6.615748e+11
2989  35284.344430  33213.661034  2.672155e+10  6.326962e+11
2990  35038.536363  33599.916169  2.650126e+10  6.418992e+11

[2991 rows x 4 columns]

In [115]:
data.isnull().sum().sum()

0

In [116]:
# load the dataset
x=data.iloc[:,[0,1,2,3]]

y = (data['High'] + data['Low']) / 2
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2)
y_train = y_train.to_numpy().reshape(-1, 1)
y_train

array([[ 7015.77001953],
       [17608.66049196],
       [  402.80349731],
       ...,
       [ 3706.89501953],
       [ 6816.93820091],
       [ 9586.27417945]])

In [117]:
# print x_train
print("Type of x_train:",type(x_train))
print("First five elements of x_train are:\n", x_train[:5]) 

Type of x_train: <class 'pandas.core.frame.DataFrame'>
First five elements of x_train are:
               High           Low        Volume     Marketcap
1805   7111.560059   6919.979980  3.652500e+09  1.191629e+11
2768  18866.286130  16351.034854  6.139684e+10  3.182320e+11
510     412.425995    393.181000  2.658010e+07  5.303651e+09
2054   3489.739395   3298.131962  4.343372e+09  5.772869e+10
2718  10680.508198  10562.507126  3.779946e+10  1.974858e+11


In [118]:
# print x_train
print("Type of x_test:",type(x_test))
print("First five elements of x_test are:\n", x_test[:5]) 

Type of x_test: <class 'pandas.core.frame.DataFrame'>
First five elements of x_test are:
               High           Low        Volume     Marketcap
338     495.045013    431.269012  4.964760e+07  5.506314e+09
2328  10441.489016  10226.596900  1.410986e+10  1.858092e+11
659     245.774994    232.313995  2.736310e+07  3.373706e+09
2422   7171.168703   6903.682773  2.021327e+10  1.255156e+11
476     499.369995    443.851013  5.078380e+07  6.072260e+09


In [119]:
# print y_train
print("Type of y_train:",type(y_train))
print("First five elements of y_train are:\n", y_train[:5]) 

Type of y_train: <class 'numpy.ndarray'>
First five elements of y_train are:
 [[ 7015.77001953]
 [17608.66049196]
 [  402.80349731]
 [ 3393.93567828]
 [10621.50766201]]


In [120]:
# print x_train
print("Type of y_test:",type(y_test))
print("First five elements of y_test are:\n", y_test[:5]) 

Type of y_test: <class 'pandas.core.series.Series'>
First five elements of y_test are:
 338       463.157013
2328    10334.042958
659       239.044495
2422     7037.425738
476       471.610504
dtype: float64


In [129]:
x_train.insert(0,1,1)
x_train

1          High           Low        Volume     Marketcap
1805  1   7111.560059   6919.979980  3.652500e+09  1.191629e+11
2768  1  18866.286130  16351.034854  6.139684e+10  3.182320e+11
510   1    412.425995    393.181000  2.658010e+07  5.303651e+09
2054  1   3489.739395   3298.131962  4.343372e+09  5.772869e+10
2718  1  10680.508198  10562.507126  3.779946e+10  1.974858e+11
...  ..           ...           ...           ...           ...
2514  1   5371.348516   4981.909413  3.862264e+10  9.549994e+10
2347  1   8393.041645   8227.695703  1.312571e+10  1.508238e+11
1608  1   3819.209961   3594.580078  9.281140e+08  6.289207e+10
2541  1   6965.616638   6668.259764  3.861931e+10  1.254222e+11
2575  1   9823.002288   9349.546071  4.008425e+10  1.777454e+11

[2093 rows x 5 columns]

In [130]:
class MultipleLinearRegression:
    def __init__(self):
        self.intercept = None
        self.coefficient = None
        
    def fit(self, x_train, y_train):
        # Add a column of ones to the x_train matrix for the intercept term
        #x+index to add+1+coloumns      
        
        
        #calculate the learnoing parameter for given uquation        
        beta = np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
        
        # intercept and coefficients
        self.intercept = beta[0]
        self.coefficient = beta[1:]
        print(beta)
    def predict(self, x_test):
        if self.intercept is None or self.coefficient is None:
            raise ValueError("Model has not been trained. Call fit() first.")
        y_pred=np.dot(x_test,self.coefficient)+ self.intercept
        
        return y_pred

In [134]:

obj=MultipleLinearRegression()
obj.fit(x_train,y_train)
y_pred=obj.predict(x_test)
y_pred

[[ 1.35543132e-09]
 [ 5.00000000e-01]
 [ 5.00000000e-01]
 [-3.52709813e-21]
 [ 1.27650512e-20]]


array([[  463.15701294],
       [10334.04295835],
       [  239.04449463],
       [ 7037.42573791],
       [  471.61050415],
       [  241.27449799],
       [  226.4529953 ],
       [ 9357.58607755],
       [10157.82317947],
       [18356.11142033],
       [ 6725.02001953],
       [ 6550.61      ],
       [14960.75      ],
       [  855.57998657],
       [ 1053.60501099],
       [ 3676.39460292],
       [55202.80189704],
       [10056.82073663],
       [ 9203.18994141],
       [  361.57099915],
       [  436.02050781],
       [57001.59082758],
       [  382.38450623],
       [11385.9371009 ],
       [  240.41400147],
       [ 8712.21972657],
       [  111.4980011 ],
       [19171.48529787],
       [  289.91749573],
       [  131.86999512],
       [  730.84500122],
       [ 9975.1645785 ],
       [ 9412.44957613],
       [  380.80050659],
       [  816.84301758],
       [  402.6459961 ],
       [  833.66998291],
       [  130.11000061],
       [10906.0243969 ],
       [  429.09849548],


In [146]:
SSE=0
SAE=0
sum_square=0
for i in range(len(y_test)):
    SSE+=(int(y_test[i])-int(y_pred[i]))**2
    SAE+=abs(int(y_test[i])-int(y_pred[i]))
SSE/=len(y_test)
SAE/=len(y_test)

In [147]:
print("mean squared error  :   ",SSE)
print("mean absolute error   :   ",SAE)

mean squared error  :    0.0011135857461024498
mean absolute error   :    0.0011135857461024498
